from .. import ReadBatch as ReadBatch_new
from .Read import Read

# NOTE: this workflow is for reading samples
# that were saved with text headers generated by SPEC 

class ReadBatch(ReadBatch_new.ReadBatch):

    def __init__(self):
        super(ReadBatch,self).__init__()
        self.add_operation('read',Read())

