from collections import OrderedDict
import copy

from paws import pawstools

from paws.workflows.Workflow import Workflow 
from paws.workflows.IO.BL15 import ReadBatch as ReadBatch_new
from paws.workflows.IO.BL15.LEGACY.Read import Read

# NOTE: this workflow is for reading samples
# that were saved with text headers generated by SPEC 

inputs = copy.deepcopy(ReadBatch_new.inputs) 
outputs = copy.deepcopy(ReadBatch_new.outputs) 

class ReadBatch(Workflow):

    def __init__(self):
        super(ReadBatch,self).__init__(inputs,outputs)
        self.batch_read_wf = ReadBatch_new.ReadBatch()
        # swap out the read wf 
        self.batch_read_wf.add_operation('read',Read())

    def run(self):
        self.batch_read_wf.ops_enabled.update(self.ops_enabled) 
        self.outputs = self.batch_read_wf.run_with(**self.inputs)
        return self.outputs

